apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animal-imageclassifier
  template:
    metadata:
      labels:
        app: animal-imageclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/cats-project/webapp:v1
        ports:
        - containerPort: 8501